#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34011
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cham.Droid.ToolkitX.Resource", IsApplication=false)]

namespace Cham.Droid.ToolkitX
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000d
			public static int ChamAutoCompleteTextViewStyle = 2130771981;
			
			// aapt resource value: 0x7f010003
			public static int ChamDatePickerStyle = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int ChamEditTextStyle = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int ChamHeaderStyle = 2130771970;
			
			// aapt resource value: 0x7f01000c
			public static int ChamSpinnerStyle = 2130771980;
			
			// aapt resource value: 0x7f010000
			public static int ChamTextStyle = 2130771968;
			
			// aapt resource value: 0x7f01000a
			public static int Currency = 2130771978;
			
			// aapt resource value: 0x7f010005
			public static int Header = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int HeaderStyle = 2130771975;
			
			// aapt resource value: 0x7f01000b
			public static int ReadOnly = 2130771979;
			
			// aapt resource value: 0x7f010006
			public static int Required = 2130771974;
			
			// aapt resource value: 0x7f010008
			public static int Text = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int TextStyle = 2130771977;
			
			// aapt resource value: 0x7f010004
			public static int maxWidth = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int calendar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int delete_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int picture = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int splash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public static int AutoCompleteTextView = 2131099649;
			
			// aapt resource value: 0x7f060003
			public static int ChamDatePickerButton = 2131099651;
			
			// aapt resource value: 0x7f060000
			public static int ChamHeader = 2131099648;
			
			// aapt resource value: 0x7f060006
			public static int ChamSpinnerSpinner = 2131099654;
			
			// aapt resource value: 0x7f060004
			public static int ChamTextEdit_EditText = 2131099652;
			
			// aapt resource value: 0x7f060002
			public static int ChamTextView = 2131099650;
			
			// aapt resource value: 0x7f060005
			public static int Cham_TextView = 2131099653;
			
			// aapt resource value: 0x7f060007
			public static int FooEditText = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int ChamAutoCompleteTextViewLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int ChamDatePickerLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int ChamEditTextLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int ChamSpinnerLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int ChamTextViewLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int shape_line = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int spinner_row_nothing_selected = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public static int ApplicationName = 2130968582;
			
			// aapt resource value: 0x7f040000
			public static int Camera = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int Delete = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int Gallery = 2130968578;
			
			// aapt resource value: 0x7f040005
			public static int Hello = 2130968581;
			
			// aapt resource value: 0x7f040003
			public static int HowDoYouWantToSetYourPicture = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int Options = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public static int ChamDatePicker = 2131034114;
			
			// aapt resource value: 0x7f050001
			public static int ChamEditText = 2131034113;
			
			// aapt resource value: 0x7f050008
			public static int ChamSpinner = 2131034120;
			
			// aapt resource value: 0x7f050000
			public static int ChamTextView = 2131034112;
			
			// aapt resource value: 0x7f050004
			public static int ClearableEditText = 2131034116;
			
			// aapt resource value: 0x7f050007
			public static int DashboardButton = 2131034119;
			
			// aapt resource value: 0x7f050003
			public static int Header = 2131034115;
			
			// aapt resource value: 0x7f050006
			public static int MaxWidthLinearLayout = 2131034118;
			
			// aapt resource value: 0x7f050005
			public static int TextView = 2131034117;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ChamDatePicker;
			
			public static int[] ChamDroidToolkitTheme = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 3
			public static int ChamDroidToolkitTheme_ChamDatePickerStyle = 3;
			
			// aapt resource value: 1
			public static int ChamDroidToolkitTheme_ChamEditTextStyle = 1;
			
			// aapt resource value: 2
			public static int ChamDroidToolkitTheme_ChamHeaderStyle = 2;
			
			// aapt resource value: 0
			public static int ChamDroidToolkitTheme_ChamTextStyle = 0;
			
			public static int[] ChamDroidToolkitXTheme = new int[] {
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public static int ChamDroidToolkitXTheme_ChamAutoCompleteTextViewStyle = 1;
			
			// aapt resource value: 0
			public static int ChamDroidToolkitXTheme_ChamSpinnerStyle = 0;
			
			public static int[] ChamEditText = new int[] {
					16843091,
					16843092,
					16843094,
					16843101,
					16843296,
					16843364,
					2130771979};
			
			// aapt resource value: 6
			public static int ChamEditText_ReadOnly = 6;
			
			// aapt resource value: 5
			public static int ChamEditText_android_imeOptions = 5;
			
			// aapt resource value: 4
			public static int ChamEditText_android_inputType = 4;
			
			// aapt resource value: 1
			public static int ChamEditText_android_lines = 1;
			
			// aapt resource value: 0
			public static int ChamEditText_android_maxLines = 0;
			
			// aapt resource value: 2
			public static int ChamEditText_android_minLines = 2;
			
			// aapt resource value: 3
			public static int ChamEditText_android_singleLine = 3;
			
			public static int[] ChamHeader = new int[] {
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public static int ChamHeader_Header = 0;
			
			// aapt resource value: 2
			public static int ChamHeader_HeaderStyle = 2;
			
			// aapt resource value: 1
			public static int ChamHeader_Required = 1;
			
			public static int[] ChamText = new int[] {
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 2
			public static int ChamText_Currency = 2;
			
			// aapt resource value: 0
			public static int ChamText_Text = 0;
			
			// aapt resource value: 1
			public static int ChamText_TextStyle = 1;
			
			public static int[] MaxWidthLinearLayout = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public static int MaxWidthLinearLayout_maxWidth = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
